### ISSUE TITLE
If my PCD does not have intensity or reflectivity, is the Proj_GFC method still applicable？

### ISSUE THREAD

**Issue by ywfwyht** [kaist-avelab/K-Lane#12]
hi @dhepaek 

  If my PCD does not have intensity or reflectivity, is the Proj_GFC method still applicable？

**Comment by DongHeePaek** [comment]
Hello, @ywfwyht

Actually, I haven't tried the Proj-GFC without intensity and reflectivity.

However, I am fairly certain that the intensity and reflectivity play an important role in lane detection because the points closest to the lines have significantly higher values than the others.

So LiDAR lane detection without those values may be similar to predicting lanes only with the shape of their surroundings, leading to weakening detection performance.

Thank you.

**Comment by ywfwyht** [comment]
hi @dhepaek ，Thank you for your reply。
What about the situation where my PCD data can only have intensity without reflectivity right now? To create a fake reflectivity or to take away the reflectivity？

**Comment by DongHeePaek** [comment]
Hello, @ywfwyht 

As previously stated, we have not attempted and do not recommend training the network without intensity or reflectivity, which may be essential in lane detection.
However, the experiment results with training the network without intensity or reflectivity, resulting in one-channel BEV image input to the BEV projector, could be interesting.

Thank you.
